services:
  app:
    container_name: pyload-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    networks:
      - shared_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  shared_net:
    external: true
