services:
  app:
    container_name: gramps-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    networks:
      - shared_net
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 75s

networks:
  shared_net:
    external: true
